---
abstract: "WebService::Mandrill - an interface to mandrillapp.com's RESTful Web API using Web::API"
author:
  - 'Tobias Kirschstein <lev@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.020, CPAN::Meta::Converter version 2.142060'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: WebService-Mandrill
requires:
  Modern::Perl: '0'
  Mouse: '0'
  Web::API: '0'
resources:
  bugtracker: https://github.com/nupfel/WebService-Mandrill/issues
  homepage: https://github.com/nupfel/WebService-Mandrill/wiki
  repository: git://github.com/nupfel/WebService-Mandrill.git
version: '0.7'
